spring:
  application:
    name: trade-service
server:
  port: 8080
  servlet:
    context-path: /trade-service

---
spring:
  profiles: test
  jpa:
    show-sql: true
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE